version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11-browsers

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: dependency-cache
          paths:
            - ~/.cache/yarn
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Run linter
          command: yarn run lint
