# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TodoDomiDeliverer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TodoDomiDeliverer
  pod 'Fabric'
  pod 'Crashlytics'

  target 'TodoDomiDeliverer-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TodoDomiDelivererTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
