# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TodoDomiDeliverer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  rn_path = '../node_modules/react-native'

  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => "#{rn_path}/ReactCommon/yoga/Yoga.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end

      if target.name == "yoga"
        target.remove_from_project
      end
    end
  end

  # Pods for TodoDomiDeliverer
  target 'TodoDomiDeliverer-tvOSTests' do
    inherit! :search_paths

  end

  target 'TodoDomiDelivererTests' do
    inherit! :search_paths
    # Pods for testing
  end

end